In [18]:
import tensorflow as tf

sess = tf.Session()

# learning rate, alpha
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)

In [19]:
x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data = [1, 2, 3, 4, 5]


W1 = tf.Variable( tf.random_uniform([1], -1.0, 1.0) )
W2 = tf.Variable( tf.random_uniform([1], -1.0, 1.0) )
b = tf.Variable( tf.random_uniform([1], -1.0, 1.0) )

hypothesis = W1 * x1_data + W2 * x2_data + b
cost = tf.reduce_mean( tf.square(hypothesis - y_data) )
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess.run(init)

for step in xrange(2001):
    sess.run(train)
    if step % 20 == 0:
        print step, sess.run(cost), sess.run(W1), sess.run(W2), sess.run(b)


0 1.08535 [ 1.18358362] [ 0.80942214] [ 0.7435239]
20 0.0215703 [ 0.90847605] [ 0.89140707] [ 0.3481712]
40 0.00624549 [ 0.95075148] [ 0.94156712] [ 0.18734764]
60 0.00180833 [ 0.97349977] [ 0.96855783] [ 0.10081004]
80 0.000523586 [ 0.98574054] [ 0.98308122] [ 0.05424495]
100 0.0001516 [ 0.99232709] [ 0.99089617] [ 0.02918876]
120 4.38952e-05 [ 0.99587125] [ 0.99510133] [ 0.0157062]
140 1.27091e-05 [ 0.99777836] [ 0.99736404] [ 0.00845134]
160 3.67985e-06 [ 0.99880463] [ 0.99858165] [ 0.00454766]
180 1.06544e-06 [ 0.99935675] [ 0.99923676] [ 0.00244703]
200 3.0852e-07 [ 0.99965388] [ 0.99958932] [ 0.00131674]
220 8.93456e-08 [ 0.99981368] [ 0.99977905] [ 0.00070854]
240 2.58577e-08 [ 0.99989974] [ 0.99988109] [ 0.00038122]
260 7.49249e-09 [ 0.99994606] [ 0.99993604] [ 0.00020514]
280 2.16543e-09 [ 0.99997097] [ 0.99996561] [ 0.00011038]
300 6.26872e-10 [ 0.99998432] [ 0.99998146] [  5.93936566e-05]
320 1.82342e-10 [ 0.9999916] [ 0.99999005] [  3.19850478e-05]
340 5.30122e-11 [ 0.99999

In [20]:
# using matrix excluding b


x_data = [ [1.0, 0.0, 3.0, 0.0, 5.0], [0.0, 2.0, 0.0, 4.0, 0.0] ]
y_data = [1, 2, 3, 4, 5]

W = tf.Variable( tf.random_uniform([1,2], -1.0, 1.0) )
b = tf.Variable( tf.random_uniform([1], -1.0, 1.0) )

hypothesis = tf.matmul(W, x_data) + b
cost = tf.reduce_mean( tf.square(hypothesis - y_data) )
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess.run(init)

for step in xrange(2001):
    sess.run(train)
    if step % 20 == 0:
        print step, sess.run(cost), sess.run(W), sess.run(b)


0 0.545707 [[ 1.02849233  0.73003268]] [ 0.84086978]
20 0.0318853 [[ 0.88872367  0.86797118]] [ 0.42331144]
40 0.00923211 [[ 0.94012302  0.92895651]] [ 0.22777984]
60 0.00267308 [[ 0.96778089  0.96177214]] [ 0.12256625]
80 0.000773967 [[ 0.98266315  0.97942996]] [ 0.06595173]
100 0.000224096 [[ 0.99067122  0.98893142]] [ 0.03548802]
120 6.48843e-05 [[ 0.99498022  0.99404413]] [ 0.0190958]
140 1.8787e-05 [[ 0.9972989   0.99679518]] [ 0.01027528]
160 5.4398e-06 [[ 0.9985466   0.99827552]] [ 0.00552906]
180 1.57516e-06 [[ 0.99921781  0.99907202]] [ 0.00297514]
200 4.55986e-07 [[ 0.99957919  0.99950069]] [ 0.00160092]
220 1.32011e-07 [[ 0.99977356  0.9997313 ]] [ 0.00086146]
240 3.82308e-08 [[ 0.99987811  0.9998554 ]] [ 0.00046354]
260 1.10738e-08 [[ 0.99993438  0.99992222]] [ 0.00024942]
280 3.20814e-09 [[ 0.99996471  0.9999581 ]] [ 0.00013422]
300 9.28074e-10 [[ 0.99998111  0.99997747]] [  7.22267141e-05]
320 2.69316e-10 [[ 0.99998981  0.9999879 ]] [  3.88624248e-05]
340 7.76595e-11 [[ 0

In [22]:
# using matrix including b


x_data = [ [1, 1, 1, 1, 1], [1.0, 0.0, 3.0, 0.0, 5.0], [0.0, 2.0, 0.0, 4.0, 0.0] ]
y_data = [1, 2, 3, 4, 5]

W = tf.Variable( tf.random_uniform([1,3], -1.0, 1.0) )

hypothesis = tf.matmul(W, x_data)
cost = tf.reduce_mean( tf.square(hypothesis - y_data) )
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess.run(init)

for step in xrange(2001):
    sess.run(train)
    if step % 20 == 0:
        print step, sess.run(cost), sess.run(W)


0 4.64769 [[ 0.41535389  1.70357251  0.94636685]]
20 0.00231292 [[ 0.11401085  0.97003073  0.9644407 ]]
40 0.000669687 [[ 0.06134806  0.98387331  0.98086584]]
60 0.000193902 [[ 0.03301087  0.99132252  0.98970407]]
80 5.61425e-05 [[ 0.01776283  0.99533057  0.99445981]]
100 1.62556e-05 [[ 0.00955805  0.99748743  0.99701887]]
120 4.70675e-06 [[ 0.00514309  0.99864799  0.99839586]]
140 1.36266e-06 [[ 0.00276744  0.99927253  0.99913687]]
160 3.9452e-07 [[ 0.00148914  0.99960858  0.9995355 ]]
180 1.14287e-07 [[  8.01321468e-04   9.99789357e-01   9.99750078e-01]]
200 3.31062e-08 [[  4.31190914e-04   9.99886632e-01   9.99865532e-01]]
220 9.57001e-09 [[  2.31992221e-04   9.99938965e-01   9.99927640e-01]]
240 2.77266e-09 [[  1.24832586e-04   9.99967217e-01   9.99961078e-01]]
260 8.00105e-10 [[  6.71305170e-05   9.99982417e-01   9.99979079e-01]]
280 2.30389e-10 [[  3.61170241e-05   9.99990523e-01   9.99988735e-01]]
300 6.73708e-11 [[  1.94372606e-05   9.99994814e-01   9.99993920e-01]]
320 1.95655

In [24]:
# using txt file

import numpy as np

xy = np.loadtxt('lab_04_train.txt', unpack=True, dtype='float32')
x_data = xy[0:-1]
y_data = xy[-1]

print x_data
print y_data


W = tf.Variable( tf.random_uniform([1,len(x_data)], -1.0, 1.0) )

hypothesis = tf.matmul(W, x_data)
cost = tf.reduce_mean( tf.square(hypothesis - y_data) )

train = optimizer.minimize(cost)

init = tf.global_variables_initializer()
sess.run(init)

for step in xrange(2001):
    sess.run(train)
    if step % 20 == 0:
        print step, sess.run(cost), sess.run(W)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  3.  0.  5.]
 [ 0.  2.  0.  4.  0.]]
[ 1.  2.  3.  4.  5.]
0 3.83525 [[ 0.47589701  1.60895729  0.97038627]]
20 0.00400144 [[ 0.14995939  0.96058071  0.95322853]]
40 0.00115858 [[ 0.08069162  0.9787885   0.97483271]]
60 0.00033546 [[ 0.04341938  0.98858625  0.98645765]]
80 9.71292e-05 [[ 0.02336355  0.99385834  0.99271297]]
100 2.81227e-05 [[ 0.0125717   0.99669522  0.99607891]]
120 8.14258e-06 [[ 0.00676475  0.99822181  0.99789011]]
140 2.35763e-06 [[ 0.00364006  0.99904317  0.99886471]]
160 6.82586e-07 [[ 0.00195869  0.99948508  0.99938911]]
180 1.97699e-07 [[ 0.001054    0.99972296  0.99967128]]
200 5.7258e-08 [[  5.67106646e-04   9.99850869e-01   9.99823093e-01]]
220 1.6559e-08 [[  3.05137073e-04   9.99919772e-01   9.99904811e-01]]
240 4.79201e-09 [[  1.64184035e-04   9.99956846e-01   9.99948800e-01]]
260 1.38532e-09 [[  8.83239991e-05   9.99976814e-01   9.99972463e-01]]
280 4.03307e-10 [[  4.75782654e-05   9.99987543e-01   9.99985158e-01]]
300 1.16