# XOR input: Logistic Regression vs Neural Networks

In [5]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('lab_09_train.txt', unpack=True)

learning_rate = 0.1

## using logistic regression

In [7]:
x_data = xy[0:-1]
y_data = xy[-1]

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable( tf.random_uniform([1,len(x_data)], -1.0, 1.0) )

h = tf.matmul(W, X)
hypothesis = tf.div( 1.0, 1.0 + tf.exp(-h) )
cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis) )

optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in xrange(20000):
        sess.run( optimizer, feed_dict={X: x_data, Y: y_data} )
        if step % 5000 == 0:
            print step, sess.run( cost, feed_dict={X: x_data, Y: y_data} ), sess.run(W)
            
    # test model
    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)
    
    # calculate accuracy
    accuracy = tf.reduce_mean( tf.cast(correct_prediction, 'float') )
    print sess.run( [hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X: x_data, Y: y_data} )
    print "Accuracy: ", accuracy.eval({X: x_data, Y: y_data})

0 0.721668 [[ 0.1005684   0.62609041]]
5000 0.693147 [[  3.02305097e-08   5.75125085e-08]]
10000 0.693147 [[  3.02305097e-08   5.75125085e-08]]
15000 0.693147 [[  3.02305097e-08   5.75125085e-08]]
[array([[ 0.5,  0.5,  0.5,  0.5]], dtype=float32), array([[ 1.,  1.,  1.,  1.]], dtype=float32), array([[False,  True,  True, False]], dtype=bool), 0.5]
Accuracy:  0.5


## using simple neural network

In [9]:
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2, 2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [2, 1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

L2 =  tf.sigmoid( tf.matmul(X, W1) + b1 )
hypothesis = tf.sigmoid( tf.matmul(L2, W2) + b2 )

cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1.0 - hypothesis) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(20000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % 5000 == 0:
            print step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W1), sess.run(W2), b1, b2
            
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print sess.run( [hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X:x_data, Y:y_data})
    print "Accuracy:", accuracy.eval({X: x_data, Y: y_data})


0 0.709884 [[-0.52016264  0.15535761]
 [-0.72850347 -0.22847234]] [[ 0.33279434]
 [ 0.49725112]] Tensor("Bias1_3/read:0", shape=(2,), dtype=float32) Tensor("Bias2_3/read:0", shape=(1,), dtype=float32)
5000 0.489938 [[-3.94420052 -0.64380538]
 [-4.02758503 -1.14481759]] [[-4.31581259]
 [ 1.75721657]] Tensor("Bias1_3/read:0", shape=(2,), dtype=float32) Tensor("Bias2_3/read:0", shape=(1,), dtype=float32)
10000 0.0269741 [[-6.22557592 -4.43546677]
 [-6.25414276 -4.43960714]] [[-9.49466705]
 [ 8.88570404]] Tensor("Bias1_3/read:0", shape=(2,), dtype=float32) Tensor("Bias2_3/read:0", shape=(1,), dtype=float32)
15000 0.011497 [[-6.63398981 -5.03386545]
 [-6.65269375 -5.03678417]] [[-10.95162868]
 [ 10.46949577]] Tensor("Bias1_3/read:0", shape=(2,), dtype=float32) Tensor("Bias2_3/read:0", shape=(1,), dtype=float32)
[array([[ 0.00591452],
       [ 0.99352914],
       [ 0.99351996],
       [ 0.0099033 ]], dtype=float32), array([[ 0.],
       [ 1.],
       [ 1.],
       [ 0.]], dtype=float32), arr

## using wide neural network

In [10]:
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [10,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

L2 =  tf.sigmoid( tf.matmul(X, W1) + b1 )
hypothesis = tf.sigmoid( tf.matmul(L2, W2) + b2 )

cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1.0 - hypothesis) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(20000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % 5000 == 0:
            print step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W1), sess.run(W2), b1, b2
            
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print sess.run( [hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X:x_data, Y:y_data})
    print "Accuracy:", accuracy.eval({X: x_data, Y: y_data})

0 0.695587 [[-0.983845   -0.19860178 -0.69784486 -0.17064226  0.19575037 -0.74589014
  -0.56897199 -0.07703776 -0.0941787  -0.58280563]
 [-0.19551569  0.32156786  0.69738013 -0.62232763 -0.23675887 -0.10448418
   0.16367304  0.92645949  0.29119799 -0.48097354]] [[ 0.62434852]
 [ 0.57620496]
 [-0.79878217]
 [-0.1515685 ]
 [-0.15949166]
 [-0.23786634]
 [-0.83737874]
 [ 0.6933707 ]
 [ 0.59509647]
 [-0.82000744]] Tensor("Bias1_4/read:0", shape=(10,), dtype=float32) Tensor("Bias2_4/read:0", shape=(1,), dtype=float32)
5000 0.0336512 [[-4.76701927 -2.03027964 -4.47518921 -0.36735728  0.18886404 -1.20152617
   0.12320431  1.0800072  -1.55973887 -4.66221476]
 [ 3.04962182  0.31679446  5.77711773 -0.84629589 -0.2766045  -0.21131141
   0.6679731   1.37697423 -0.07545896 -4.70585251]] [[ 5.7908988 ]
 [ 2.38892484]
 [-7.43508673]
 [ 1.15601361]
 [ 0.29552561]
 [ 1.46285844]
 [-0.45825627]
 [ 1.24527311]
 [ 2.15297675]
 [-5.96628714]] Tensor("Bias1_4/read:0", shape=(10,), dtype=float32) Tensor("Bias

## using deep neural network

In [11]:
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,5], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [5,4], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform( [4,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([5]), name="Bias1")
b2 = tf.Variable(tf.zeros([4]), name="Bias2")
b3 = tf.Variable(tf.zeros([1]), name="Bias3")

L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
L3 =  tf.sigmoid(tf.matmul(L2,W2)+b2)
hypothesis = tf.sigmoid( tf.matmul(L3,W3) + b3)

cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1.0 - hypothesis) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(20001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % 5000 == 0:
            print step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W1), sess.run(W2), sess.run(W3), b1, b2, b3
            
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print sess.run( [hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X:x_data, Y:y_data})
    print "Accuracy:", accuracy.eval({X: x_data, Y: y_data})

0 0.695983 [[-0.2166995   0.45006603 -0.23637293  0.25363451  0.04967713]
 [ 0.90487099  0.16599664  0.49083501 -0.68595636 -0.6853469 ]] [[ 0.3251698  -0.94339389  0.48530671  0.09753107]
 [ 0.35090142  0.42844689 -0.82836026  0.19950505]
 [-0.65185779 -0.06655259 -0.62524444  0.38169926]
 [-0.16463098  0.26131105  0.58416915 -0.05429392]
 [ 0.39464092 -0.48898676 -0.98763943 -0.61004072]] [[ 0.32677791]
 [ 0.39432114]
 [-0.52228761]
 [-0.59872323]] Tensor("Bias1_5/read:0", shape=(5,), dtype=float32) Tensor("Bias2_5/read:0", shape=(4,), dtype=float32) Tensor("Bias3/read:0", shape=(1,), dtype=float32)
5000 0.6891 [[-0.65491605  0.76230091 -0.25311598  0.29145241  0.16359532]
 [ 1.30647552  0.69629109  0.54480207 -0.71090603 -0.62630939]] [[ 0.26453128 -1.19685924  0.56283319  0.23140848]
 [ 0.42178407  0.52909595 -0.9242934   0.09887692]
 [-0.63298601 -0.13234858 -0.65406108  0.38009432]
 [-0.17808551  0.29828507  0.66638905 -0.03764731]
 [ 0.38094816 -0.46569562 -0.91279739 -0.5899413

## TensorBoard

In [12]:
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32, name='X-input')
Y = tf.placeholder(tf.float32, name='Y-input')

W1 = tf.Variable(tf.random_uniform( [2, 2], -1.0, 1.0), name="Weight1")
W2 = tf.Variable(tf.random_uniform( [2, 1], -1.0, 1.0), name="Weight2")

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
with tf.name_scope("layer2") as scope:
    L2 =  tf.sigmoid(tf.matmul(X, W1) + b1)

with tf.name_scope("layer3") as scope:
    hypothesis =  tf.sigmoid(tf.matmul(L2, W2) + b2)

# Cost function 
with tf.name_scope("cost") as scope:
    cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1.0 - hypothesis) )
    cost_summ = tf.summary.scalar("cost", cost)
    
with tf.name_scope("train") as scope:
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

    
# Add histogram
w1_hist = tf.summary.histogram("weights1", W1)
w2_hist = tf.summary.histogram("weights2", W2)

b1_hist = tf.summary.histogram("biases1", b1)
b2_hist = tf.summary.histogram("biases2", b2)

y_hist = tf.summary.histogram("y", Y)


init = tf.global_variables_initializer()
merged = tf.summary.merge_all()

with tf.Session() as sess:
    
    writer = tf.summary.FileWriter("./logs/xor_logs", sess.graph)
    
    sess.run(init)
    
    for step in range(200000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 20000 == 0:
            print step
            summary, _ = sess.run([merged, optimizer], feed_dict={X: x_data, Y: y_data})
            writer.add_summary(summary, step)
            
            

0
20000
40000
60000
80000
100000
120000
140000
160000
180000
