# XOR input: Logistic Regression vs Neural Networks

In [34]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('lab_09_train.txt', unpack=True)

learning_rate = 0.1

## using logistic regression

In [35]:
x_data = xy[0:-1]
y_data = xy[-1]

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable( tf.random_uniform([1,len(x_data)], -1.0, 1.0) )

h = tf.matmul(W, X)
hypothesis = tf.div( 1.0, 1.0 + tf.exp(-h) )
cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis) )

optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in xrange(1000):
        sess.run( optimizer, feed_dict={X: x_data, Y: y_data} )
        if step % 200 == 0:
            print step, sess.run( cost, feed_dict={X: x_data, Y: y_data} ), sess.run(W)
            
    # test model
    correct_prediction = tf.equal(tf.floor(hypothesis + 0.5), Y)
    
    # calculate accuracy
    accuracy = tf.reduce_mean( tf.cast(correct_prediction, 'float') )
    print sess.run( [hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X: x_data, Y: y_data} )
    print "Accuracy: ", accuracy.eval({X: x_data, Y: y_data})

0 0.724729 [[-0.42890105  0.8292616 ]]
200 0.695232 [[-0.17779182  0.18735065]]
400 0.693317 [[-0.05206103  0.05227882]]
600 0.693161 [[-0.01488751  0.01489246]]
800 0.693148 [[-0.0042493   0.00424948]]
[array([[ 0.5       ,  0.50030512,  0.49969488,  0.5       ]], dtype=float32), array([[ 1.,  1.,  0.,  1.]], dtype=float32), array([[False,  True, False, False]], dtype=bool), 0.25]
Accuracy:  0.25


## using simple neural network

In [37]:
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [2,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

L2 =  tf.sigmoid( tf.matmul(X, W1) + b1 )
hypothesis = tf.sigmoid( tf.matmul(L2, W2) + b2 )

cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1.0 - hypothesis) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(10001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % 1000 == 0:
            print step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W1), sess.run(W2), b1, b2
            
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print sess.run( [hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X:x_data, Y:y_data})
    print "Accuracy:", accuracy.eval({X: x_data, Y: y_data})


0 0.724065 [[ 0.25141147 -0.47825217]
 [ 0.04944712 -0.71774411]] [[-0.53642452]
 [-0.65635574]] Tensor("Bias1_19/read:0", shape=(2,), dtype=float32) Tensor("Bias2_19/read:0", shape=(1,), dtype=float32)
1000 0.675531 [[ 0.27291998 -1.26491749]
 [ 0.08140468 -1.34758723]] [[-0.36545324]
 [-1.13584471]] Tensor("Bias1_19/read:0", shape=(2,), dtype=float32) Tensor("Bias2_19/read:0", shape=(1,), dtype=float32)
2000 0.579658 [[ 0.48194373 -2.92575336]
 [ 0.28653267 -2.92920423]] [[-0.52352142]
 [-3.01487732]] Tensor("Bias1_19/read:0", shape=(2,), dtype=float32) Tensor("Bias2_19/read:0", shape=(1,), dtype=float32)
3000 0.465014 [[ 1.10469174 -4.36050749]
 [ 0.93520147 -4.33688688]] [[-1.74178147]
 [-4.64500952]] Tensor("Bias1_19/read:0", shape=(2,), dtype=float32) Tensor("Bias2_19/read:0", shape=(1,), dtype=float32)
4000 0.20257 [[ 2.47304678 -5.23244333]
 [ 2.46688247 -5.20922804]] [[-4.78555059]
 [-6.11894512]] Tensor("Bias1_19/read:0", shape=(2,), dtype=float32) Tensor("Bias2_19/read:0", s

## using wide neural network

In [40]:
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [10,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

L2 =  tf.sigmoid( tf.matmul(X, W1) + b1 )
hypothesis = tf.sigmoid( tf.matmul(L2, W2) + b2 )

cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1.0 - hypothesis) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(10001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % 2000 == 0:
            print step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W1), sess.run(W2), b1, b2
            
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print sess.run( [hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X:x_data, Y:y_data})
    print "Accuracy:", accuracy.eval({X: x_data, Y: y_data})

0 0.70845 [[ 0.74515533 -0.50818598 -0.79440057  0.68156415 -0.42213017 -0.34318712
  -0.37065095 -0.59700227  0.93832636  0.14007711]
 [ 0.26808497 -0.78408492  0.32111916 -0.18162203  0.11288434  0.56750906
   0.8782028   0.72991693 -0.90545374  0.46122867]] [[-0.8570168 ]
 [-0.04446406]
 [ 0.34817827]
 [ 0.34697685]
 [-0.12157334]
 [ 0.51242834]
 [ 0.26394835]
 [ 0.29803249]
 [ 0.32545871]
 [-0.26988909]] Tensor("Bias1_22/read:0", shape=(10,), dtype=float32) Tensor("Bias2_22/read:0", shape=(1,), dtype=float32)
2000 0.490439 [[ 1.01396155 -2.06832838 -1.33201933  0.58450097 -0.36809659 -0.66572475
  -0.38988033 -0.97714484  2.22212601  0.1186303 ]
 [-0.26801288 -2.32680082  0.6330198  -0.11063956  0.09143887  0.50203443
   0.8105877   0.67779118 -2.94420362  0.42335624]] [[-1.19325399]
 [-2.30077219]
 [ 0.98292357]
 [ 0.0260709 ]
 [-0.09056997]
 [ 0.63786858]
 [ 0.13671546]
 [ 0.6517266 ]
 [ 2.67585373]
 [-0.35334176]] Tensor("Bias1_22/read:0", shape=(10,), dtype=float32) Tensor("Bia

## using deep neural network

In [42]:
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,5], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [5,4], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform( [4,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([5]), name="Bias1")
b2 = tf.Variable(tf.zeros([4]), name="Bias2")
b3 = tf.Variable(tf.zeros([1]), name="Bias3")

L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
L3 =  tf.sigmoid(tf.matmul(L2,W2)+b2)
hypothesis = tf.sigmoid( tf.matmul(L3,W3) + b3)

cost = -tf.reduce_mean( Y * tf.log(hypothesis) + (1 - Y) * tf.log(1.0 - hypothesis) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)


init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(20001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        
        if step % 5000 == 0:
            print step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W1), sess.run(W2), sess.run(W3), b1, b2, b3
            
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis + 0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print sess.run( [hypothesis, tf.floor(hypothesis + 0.5), correct_prediction, accuracy], feed_dict={X:x_data, Y:y_data})
    print "Accuracy:", accuracy.eval({X: x_data, Y: y_data})

0 0.802978 [[-0.46379399  0.64272016 -0.10775276  0.48951337 -0.61551243]
 [ 0.4764815   0.17342049  0.86234277  0.49106476 -0.52225053]] [[-0.60447592  0.38459185 -0.02766007  0.39930442]
 [-0.38150871  0.94408756  0.86058605  0.62110168]
 [-0.89892012  0.04086502 -0.95147735  0.4430809 ]
 [-0.24909408  0.34666494 -0.99631196 -0.58358854]
 [-0.88160431 -0.68262166  0.14342977 -0.7631216 ]] [[-0.47865319]
 [ 0.64237934]
 [ 0.92754436]
 [ 0.56082904]] Tensor("Bias1_24/read:0", shape=(5,), dtype=float32) Tensor("Bias2_24/read:0", shape=(4,), dtype=float32) Tensor("Bias3_1/read:0", shape=(1,), dtype=float32)
5000 0.527825 [[-0.57002437  3.25625181 -0.3249397   0.62389636 -1.46587586]
 [ 0.44040096  3.33243752  1.75850487  0.82671183 -1.61449432]] [[-0.37433675  0.22110975 -0.10012133  0.3517077 ]
 [-0.87393171  2.29029202  2.50022793  1.24678791]
 [-0.35293409 -0.30967438 -1.870399    0.13612255]
 [ 0.07463605  0.15097794 -1.54032648 -0.79232872]
 [-0.53588486 -1.60411596 -0.20356855 -1.0