# recurrent neural network

In [1]:
import tensorflow as tf
import numpy as np

# id -> char
char_rdic = ['h', 'e', 'l', 'o']

# char -> id
char_dic = {w : i for i, w in enumerate(char_rdic)}

ground_truth = [char_dic[c] for c in 'hello']
x_data = tf.one_hot(ground_truth[:-1], len(char_dic), 1.0, 0.0, -1)

# Configuration
rnn_size = len(char_dic) # 4
batch_size = 1
output_size = 4

rnn_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=rnn_size, input_size=None)
initial_state = rnn_cell.zero_state(batch_size, tf.float32)
initial_state_1 = tf.zeros([batch_size, rnn_cell.state_size])
X_split = tf.split(0, len(char_dic), x_data)


outputs, state = tf.nn.rnn(rnn_cell, X_split, initial_state=initial_state)

In [2]:
# shape = 1 x 16, shape = 4 x 4
logits = tf.reshape(tf.concat(1, outputs), [-1, rnn_size])        
logits.get_shape()

# a shape of [-1] flattens into 1-D
targets = tf.reshape(ground_truth[1:], [-1])
targets.get_shape()


weights = tf.ones([len(char_dic) * batch_size])
loss = tf.nn.seq2seq.sequence_loss_by_example([logits], [targets], [weights])
cost = tf.reduce_sum(loss) / batch_size
train_op = tf.train.RMSPropOptimizer(0.01, 0.9).minimize(cost)

In [3]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    
    for i in range(100):
        sess.run(train_op)
        result = sess.run(tf.argmax(logits, 1))
        print(result, [char_rdic[t] for t in result])

(array([1, 3, 0, 3]), ['e', 'o', 'h', 'o'])
(array([1, 3, 0, 3]), ['e', 'o', 'h', 'o'])
(array([1, 3, 0, 3]), ['e', 'o', 'h', 'o'])
(array([1, 3, 0, 3]), ['e', 'o', 'h', 'o'])
(array([1, 3, 0, 3]), ['e', 'o', 'h', 'o'])
(array([1, 3, 0, 3]), ['e', 'o', 'h', 'o'])
(array([1, 3, 0, 3]), ['e', 'o', 'h', 'o'])
(array([1, 1, 3, 3]), ['e', 'e', 'o', 'o'])
(array([1, 1, 3, 3]), ['e', 'e', 'o', 'o'])
(array([1, 1, 3, 3]), ['e', 'e', 'o', 'o'])
(array([1, 1, 3, 3]), ['e', 'e', 'o', 'o'])
(array([1, 1, 3, 3]), ['e', 'e', 'o', 'o'])
(array([1, 1, 2, 3]), ['e', 'e', 'l', 'o'])
(array([1, 1, 2, 3]), ['e', 'e', 'l', 'o'])
(array([1, 1, 2, 3]), ['e', 'e', 'l', 'o'])
(array([1, 2, 2, 3]), ['e', 'l', 'l', 'o'])
(array([1, 2, 2, 3]), ['e', 'l', 'l', 'o'])
(array([1, 2, 2, 3]), ['e', 'l', 'l', 'o'])
(array([1, 2, 2, 3]), ['e', 'l', 'l', 'o'])
(array([1, 2, 2, 3]), ['e', 'l', 'l', 'o'])
(array([1, 2, 2, 3]), ['e', 'l', 'l', 'o'])
(array([1, 2, 2, 3]), ['e', 'l', 'l', 'o'])
(array([1, 2, 2, 3]), ['e', 'l',