In [27]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('lab_06_train.txt', unpack=True, dtype='float32')
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.zeros([3, 3]))

hypothesis = tf.nn.softmax( tf.matmul(X, W) )

cost = tf.reduce_mean( -tf.reduce_sum(Y * tf.log(hypothesis), reduction_indices=1) )

learning_rate = tf.Variable(0.001)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

for step in xrange(2001):
    sess.run( train, feed_dict={X: x_data, Y: y_data} )
    if step % 200 == 0:
        print step, sess.run( cost, feed_dict={X: x_data, Y: y_data} ), sess.run(W)

0 1.09774 [[ -8.33333252e-05   4.16666626e-05   4.16666480e-05]
 [  1.66666694e-04   2.91666773e-04  -4.58333408e-04]
 [  1.66666636e-04   4.16666706e-04  -5.83333429e-04]]
200 1.05962 [[-0.02051384 -0.00103983  0.02155367]
 [ 0.01406438  0.01097753 -0.02504191]
 [ 0.01431208  0.03574873 -0.05006079]]
400 1.04985 [[-0.04282598 -0.00625899  0.04908497]
 [ 0.01747187  0.00156368 -0.01903554]
 [ 0.01831204  0.04954104 -0.06785304]]
600 1.0407 [[-0.06517859 -0.01176361  0.07694222]
 [ 0.01943521 -0.00848972 -0.01094548]
 [ 0.0211558   0.06118308 -0.0823388 ]]
800 1.03194 [[-0.08734013 -0.01729389  0.10463405]
 [ 0.0211172  -0.01796171 -0.00315548]
 [ 0.02396628  0.07198346 -0.09594974]]
1000 1.02354 [[-0.10928574 -0.02282181  0.13210757]
 [ 0.02266254 -0.02678034  0.00411783]
 [ 0.02685853  0.08210357 -0.10896212]]
1200 1.01547 [[-0.13101467 -0.02834092  0.15935561]
 [ 0.02409703 -0.03497621  0.01087923]
 [ 0.029832    0.091598   -0.12143001]]
1400 1.0077 [[-0.15252906 -0.03384715  0.18637

In [28]:
# test

test1 = sess.run(hypothesis, feed_dict={X: [[1, 11, 7]]})
print test1, sess.run(tf.arg_max(test1, 1))

test2 = sess.run(hypothesis, feed_dict={X: [[1, 3, 4]]})
print test2, sess.run(tf.arg_max(test2, 1))

test3 = sess.run(hypothesis, feed_dict={X: [[1, 1, 0]]})
print test3, sess.run(tf.arg_max(test3, 1))

test4 = sess.run(hypothesis, feed_dict={X: [[1, 11, 7], [1, 3, 4], [1, 1, 0]]})
print test4, sess.run(tf.arg_max(test4, 1))

[[ 0.46272627  0.35483006  0.18244371]] [0]
[[ 0.33820099  0.42101386  0.24078514]] [1]
[[ 0.27002314  0.29085544  0.4391214 ]] [2]
[[ 0.46272627  0.35483006  0.18244371]
 [ 0.33820099  0.42101386  0.24078514]
 [ 0.27002314  0.29085544  0.4391214 ]] [0 1 2]
